{
 "title": "Demo logs dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Status pie",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT  count(), status FROM r0.logs group by status"
    }
   ]
  },
  {
   "title": "Protocol pie",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(), protocol FROM r0.logs group by protocol"
    }
   ]
  },
  {
   "title": "Method Pie",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(), method FROM r0.logs group by method"
    }
   ]
  },
  {
   "title": "user-identifier Bar",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "rawSql": "SELECT count(), \"user-identifier\" FROM r0.logs group by \"user-identifier\"\n"
    }
   ]
  },
  {
   "title": "Bytes transfered",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "rawSql": "SELECT bytes,count() from r0.logs group by bytes order by bytes desc;"
    }
   ]
  },
  {
   "title": "Logs in table format",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "rawSql": "SELECT  * \nFROM  r0.logs \nLIMIT 100"
    }
   ]
  },
  {
   "title": "Logs in Bar",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "targets": [
    { "rawSql": "SELECT * FROM r0.logs LIMIT 10" }
   ]
  },
  {
   "title": "Raw Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "targets": [
    { "rawSql": "SELECT * FROM r0.logs" }
   ]
  }
 ]
}