{
 "title": "Alerts and silences overview",
 "time": { "from": "now-18h", "to": "now" },
 "panels": [
  { "title": "alerts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "alert status pie",
   "type": "piechart",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n    status,\n    count() as count\nFROM\n(\n    SELECT\n        status.state as status,\n        fingerprint\n    FROM r0.alerts\n    WHERE\n        date >= toDate(1686684884)\n        AND status != ''\n    GROUP BY\n        status,\n        fingerprint\n)\nGROUP BY status"
    }
   ]
  },
  {
   "title": "Firing alerts by instance",
   "type": "piechart",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT labels.alertname,\n       count() as count\n  FROM (\n        SELECT labels.alertname,\n               fingerprint\n          FROM r0.alerts\n         WHERE date >= toDate(1686684884)\n           AND status.state = 'firing'\n           AND annotations.dashboard = ''\n         GROUP BY labels.alertname,\n                  fingerprint\n       )\n GROUP BY \n          labels.alertname\n ORDER BY count DESC"
    }
   ]
  },
  {
   "title": "Total # of unique firing alerts",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n    count() as count\nFROM\n(\n    SELECT\n        labels.alertname,\n        fingerprint\n    FROM r0.alerts\n    WHERE\n        date >= toDate(1686684884)\n        AND status.state = 'firing'\n    GROUP BY\n        labels.alertname,\n        fingerprint\n)\nORDER BY count DESC"
    }
   ]
  },
  {
   "title": "Firing alerts by instance",
   "type": "piechart",
   "gridPos": { "h": 5, "w": 5, "x": 10, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n    labels.instance,\n    count() as count\nFROM\n(\n    SELECT\n        labels.instance,\n        status.state,\n        fingerprint\n    FROM r0.alerts\n    WHERE\n        date >= toDate(1686684884)\n        AND status.state = 'firing'\n        AND labels.instance != ''\n    GROUP BY\n        labels.instance,\n        status.state,\n        fingerprint\n)\nGROUP BY\n    status.state,\n    labels.instance\nORDER BY count DESC"
    }
   ]
  },
  {
   "title": "Firing alerts by instance",
   "type": "table",
   "gridPos": { "h": 5, "w": 5, "x": 15, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT labels.alertname,\n       count() as count\n  FROM (\n        SELECT labels.alertname,\n               fingerprint\n          FROM r0.alerts\n         WHERE date >= toDate(1686684884)\n           AND status.state = 'firing'\n           AND annotations.dashboard = ''\n         GROUP BY labels.alertname,\n                  fingerprint\n       )\n GROUP BY \n          labels.alertname\n ORDER BY count DESC"
    }
   ]
  },
  {
   "title": "Firing alerts by instance",
   "type": "table",
   "gridPos": { "h": 10, "w": 4, "x": 20, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT\n    labels.instance,\n    count() as count\nFROM\n(\n    SELECT\n        labels.instance,\n        status.state,\n        fingerprint\n    FROM r0.alerts\n    WHERE\n        date >= toDate(1686684884)\n        AND status.state = 'firing'\n        AND labels.instance != ''\n    GROUP BY\n        labels.instance,\n        status.state,\n        fingerprint\n)\nGROUP BY\n    status.state,\n    labels.instance\nORDER BY count DESC"
    }
   ]
  },
  {
   "title": "Total # of unique firing alerts",
   "type": "barchart",
   "gridPos": { "h": 5, "w": 15, "x": 0, "y": 6 },
   "targets": [
    {
     "rawSql": "SELECT\n    toStartOfFifteenMinutes(timestamp) as t,\n    count() as count\nFROM r0.alerts\nWHERE\n    date >= toDate(1686684884)\n    AND status.state = 'firing'\nGROUP BY t\nORDER BY t"
    }
   ]
  },
  {
   "title": "Alertnames with missing runbook",
   "type": "table",
   "gridPos": { "h": 5, "w": 5, "x": 15, "y": 6 },
   "targets": [
    {
     "rawSql": "SELECT labels.alertname,\n       count() as count\n  FROM (\n        SELECT labels.alertname,\n               fingerprint\n          FROM r0.alerts\n         WHERE date >= toDate(1686684884)\n           AND status.state = 'firing'\n           AND annotations.link = ''\n         GROUP BY labels.alertname,\n                  fingerprint\n       )\n GROUP BY \n          labels.alertname\n ORDER BY count DESC"
    }
   ]
  },
  {
   "title": "Instance status timeline",
   "type": "state-timeline",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 11 },
   "targets": [
    {
     "rawSql": "SELECT\n        toStartOfFifteenMinutes(timestamp) as time,\n        labels.instance,\n        status.state,\n        fingerprint\n    FROM r0.alerts\n    WHERE\n        date >= toDate(1686684884)\n        AND labels.instance != ''\n    GROUP BY\n        time,\n        status.state,\n        labels.instance,\n        fingerprint"
    }
   ]
  },
  {
   "title": "Alert label set",
   "type": "table",
   "gridPos": { "h": 6, "w": 14, "x": 10, "y": 11 },
   "targets": [
    {
     "rawSql": "SELECT (labelsmap) as labelKeys\n  FROM r0.alerts\n GROUP BY labelKeys"
    }
   ]
  },
  { "title": "silences", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "# of silences",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n    uniq( id)\nFROM r0.silences\nWHERE status.state = 'active'"
    }
   ]
  },
  {
   "title": "Silences createdBy",
   "type": "piechart",
   "gridPos": { "h": 5, "w": 4, "x": 2, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n    createdBy,\n    uniq(id) as count\nFROM r0.silences\nGROUP BY createdBy\nORDER BY count DESC"
    }
   ]
  },
  {
   "title": "Silence active vs expired",
   "type": "piechart",
   "gridPos": { "h": 5, "w": 4, "x": 6, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n    status,\n    count() as count\nFROM\n(\n    SELECT\n        status.state as status,\n        id\n    FROM r0.silences\n    WHERE\n        status != ''\n    GROUP BY\n        status,\n        id\n)\nGROUP BY status"
    }
   ]
  },
  {
   "title": "Silenced alerts",
   "type": "table",
   "gridPos": { "h": 5, "w": 14, "x": 10, "y": 18 },
   "targets": [
    {
     "rawSql": "    SELECT\n        alerts.labels.alertname,\n        alerts.status.silencedBy as id,\n        silences.createdBy as createdBy,\n        silences.matchers as silence_matchers,\n        silences.startsAt, silences.comment\n    FROM r0.alerts as alerts\n    INNER JOIN (SELECT * FROM r0.silences) AS silences USING (id)\n    GROUP BY\n        alerts.labels.alertname,\n        alerts.status.silencedBy,\n        silences.matchers, silences.createdBy, silences.startsAt, silences.comment,\n        alerts.fingerprint\n    ORDER BY silences.startsAt DESC\n    LIMIT 100"
    }
   ]
  }
 ]
}